### ISSUE TITLE
!= not recognized as operator in Sublime Text

### ISSUE THREAD

**Issue by tchapeaux** [leafo/moonscript-tmbundle#8]
The operator `!=` is not recognized correctly by Sublime Text (build 3065).

e.g. see below
![image](https://cloud.githubusercontent.com/assets/1427052/5988155/065e2e0c-a954-11e4-8736-52064b2b071c.png)

`!=` should be colorized the same way as `~=`

**Comment by spacekookie** [comment]
I mean, the `!=` operation is in there marked as a keyword operator. So not really sure why it's not doing it. (See https://github.com/leafo/moonscript-tmbundle/blob/master/Syntaxes/MoonScript.tmLanguage#L173)

Are you running the latest version?

Personally I don't use this project (I probably should) so I can't test right now

**Comment by tchapeaux** [comment]
Re-tested with the latest version of Sublime Text (build 3126) and of this project, this seems to work fine now.

The initial bug was from 2 years ago and appears to be fixed, so I think the issue can be closed.
